---
apiVersion: v1
kind: Namespace
metadata:
  name: itential
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iag
  namespace: itential
  labels:
    app: iag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iag
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: iag
    spec:
      hostname: iag01
      containers:
        - name: iag
          image: 151.117.160.82:4567/ias/itential-adv-srvcs/ias-infra-iag/ias-iag:0.5.3
          imagePullPolicy: Always
          env:
          - name: MAX_EVENT_RES
            value: "30000000"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/v2.0/poll
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: iag
  namespace: itential
spec:
  selector:
    app: iag
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: iag
  namespace: itential
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/frontend-entry-points: https
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: iag
              servicePort: 8080
